# Generated by Django 4.2.7 on 2023-11-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmodel",
            name="image",
            field=models.ImageField(unique=True, upload_to=""),
        ),
    ]
