# Generated by Django 4.2.7 on 2023-11-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smartform",
            name="image",
            field=models.EmailField(max_length=254),
        ),
    ]
