# Generated by Django 4.2.7 on 2023-11-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tes", "0002_alter_smartform_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smartform",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
